# DSCI 6001 1.1 Lab


## Applying Python Tools - Introduction to Numpy

You can easily use python to execute the same vector-matrix operations performed in the homework. This lab is designed to help you get used to using Numerical Python or **numpy** to check your homework.

In terms of evaluations, you need to be able to compute any operation **with or without** the use of a computer. This means that if we ask you to perform calculations in a test environment, you'll need to be able to **write out every step in the computation.**


### Vectors and Vector Computations

A vector in python might be represented with the standard **list**, where each element of the vector is given by the index of the list.

In [3]:
vector = []
v1 = [3.,5., 1.]
v2 = [6., 3., 3.]

However, the list has some failures in terms of its ability to perform vector mathematic operations. For example, we cannot perform a dot product with standard lists:

In [4]:
v1*v2

TypeError: can't multiply sequence by non-int of type 'list'

From the error message, we can't multiply lists by each other. However, let us use the power of numpy to **cast** each list into a new numpy **array**:

In [25]:
import numpy as np
v1 = [3.,5., 1.]
v2 = [6., 3., 3.]

v1 = np.asarray(v1)
v2 = np.asarray(v2)


v1 = np.asarray([v1])
v2 = np.asarray([v2])
#print(v1)
#print(v2)

#print(v1.shape,v2.shape)


print(v2.T)

[[ 6.]
 [ 3.]
 [ 3.]]


In [28]:
print(np.inner(v1,v2))
print(np.outer(v1,v2))

[[ 36.]]
[[ 18.   9.   9.]
 [ 30.  15.  15.]
 [  6.   3.   3.]]


Now we can perform the **standard vector mathematics operations** on this vector.

In [23]:
v3 = v1*v2
print(v3)

[[ 18.  30.   6.]
 [  9.  15.   3.]
 [  9.  15.   3.]]


This is the creation of the new vector:

$$v_3 = v_{1i}*v_{2i}$$


As you can see, this is precisely the same as the standard [**outer or row-by-column product**](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.outer.html). 

If we wanted the **dot** or **inner** product of the two vectors we would then .sum() them up.

In [35]:
v3 = v1*v2
v3.sum()

36.0

In [36]:
np.sum(v3)

36.0

Because this set of operations and resulting abstraction is so natural, numpy has included the **dot** operation, which is more commonly used in practice:

In [18]:
v1.dot(v2)

36.0

## Using Numpy to perform vector operations

To get numpy to handle two-dimensional (or multidimensional) vectors, we need to add the dimensions to the vector. Let's check the shape of a vector:

In [25]:
v1.shape

(1, 1, 3)

Note that the second index is missing. This means that the vector is one-dimensional, and contains 3 elements.

Let's expand the dimensions of the vector, so we can manipulate it as a two-dimensional structure (allowing for comparisons to a matrix....!)

In [43]:
v1 = [3.,5.,1.]
v1 = np.expand_dims(v1, axis=0)
print v1

[[ 3.  5.  1.]]


Note that we can think of this new vector as a matrix with one row and three columns - often known as a *row vector*. In numpy we can define a *column vector* quite literally by defining it as a stack of rows:




In [50]:
v2 = np.asarray([[3.],[5.],[1.]])
print v2

[[ 3.]
 [ 5.]
 [ 1.]]


We can now build the row-by-column product by multiplying the column vector by the row vector, and you'll get the dot product:

In [51]:
v1.dot(v2)

array([[ 35.]])

In [36]:
v1 = [3.,5.,1.]
v1 = np.reshape(v1, (-1,3))
print v1

[[ 3.  5.  1.]]
