# DSCI6001 1.3 Lab (Graded)

This will be a graded laboratory assignment. It should take approximately 60 minutes. If needed you can turn it in the next day.

For questions **1) - 3)**, we will work with the following matrix.   

$${\bf A} = \begin{bmatrix}
    2 & 2 & 7 \\
    3 & 4 & 1 \\
    5 & 6 & 2 \\
\end{bmatrix}$$

**1) Matrix rank**  

Use Gauss elimination to produce the row echelon form of Matrix $\mathbf{A}$. What is the rank of $\mathbf{A}$? Use [numpy.linalg.matrix_rank](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_rank.html) to check your answer.

In [9]:
roweschA = np.array([[1, 1, (7/2)], [0, 1, (-19/2)], [0, 0, -6]])
print(roweschA)
print("Rank = 3")

[[ 1.   1.   3.5]
 [ 0.   1.  -9.5]
 [ 0.   0.  -6. ]]
Rank = 3


In [2]:
import numpy as np
A = [[2, 2, 7], [3, 4, 1], [5, 6, 2]]
np.linalg.matrix_rank(A)

3

**2) Determinant**  

Calculate the determinant of $\mathbf{A}$ by hand, then use [numpy.linalg.det](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.det.html) to check your answer.

In [14]:
np.linalg.det(A)

-11.999999999999979

**3) Matrix inversion**  

Is matrix $\mathbf{A}$ invertible? If so, use [numpy.linalg.inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) to find its inverse.

In [15]:
#yes, it is invertible because Det(A) != 0

In [16]:
np.linalg.inv(A)

array([[-0.16666667, -3.16666667,  2.16666667],
       [ 0.08333333,  2.58333333, -1.58333333],
       [ 0.16666667,  0.16666667, -0.16666667]])

**4) Programming practice**  

In yesterday's lecture you were assigned to solve the following problems from the textbook:

Problem Set 7.3: 1, 3, 5, 7, 11, 13.

1. Create Numpy arrays to represent the 6 linear systems you solved by hand yesterday in Problem Set 7.3. 

2. Solve all 6 systems using Numpy. 

Extra Credit: Store your linear systems as follows: a list of the arrays of the 6 coeffiecient matrices, and a second list, of the dependent parameters (vector $\mathbf{b}$ from the notes) of each system. Zip these two lists together. Build a loop to process these arrays, built around the following code snippet. Add code to print the solutions more elegantly. Add code to handle exceptions gracefully. 

In [7]:
onea = np.array([[5, 2], [-1, 4]])
oneb = np.array([[20.9], [-19.3]])
threea = np.array([[.5, 3.5], [-1,  5]])
threeb = np.array([5.7, 7.8])
fivea = np.array([[.8, 1.2, -.6], [2.6, 0, 1.7], [4, -7.3, -1.5]])
fiveb = np.array([-7.8, 15.3, 1.1])
sevena = np.array([[0, 1, 1], [0, 4, 6], [1, 1, 1]])
sevenb = np.array([-2, -12, 2])
elevena = np.array([[2, -1, 3], [-4, 2, -6]])
elevenb = np.array([1, 2])
thirteena = np.array([[0, 1, 1, -2], [-4, -1, -1, 2], [2, -4, 3, -1]])
thirteenb = np.array([0, -4, 3])

np.linalg.solve(onea, oneb)
np.linalg.solve(threea, threeb)
np.linalg.solve(fivea, fiveb)
np.linalg.solve(sevena, sevenb)
#np.linalg.solve(elevena, elevenb)
#np.linalg.solve(thirteena, thirteenb)

array([ 4.,  0., -2.])

In [ ]:
for n, (a1, b1) in enumerate(zip(a, b)):
    pass
