# DSCI6001-1.3.Lab-Solution

In [3]:
import numpy as np
import numpy.linalg as LA

A = np.array([[2.,2.,7.],[3.,4.,1.],[5.,6.,2.]])
print("the rank of the matrix is: ", LA.matrix_rank(A))
print("the determinant of the matrix is: ", LA.det(A))
print("the inverse of A is:\n ", LA.inv(A))

the rank of the matrix is:  3
the determinant of the matrix is:  -12.0
the inverse of A is:
  [[-0.16666667 -3.16666667  2.16666667]
 [ 0.08333333  2.58333333 -1.58333333]
 [ 0.16666667  0.16666667 -0.16666667]]


In [ ]:
a = []  # list of arrays, of coefficients to the linear system
b = []  # list of arrays, of dependent variables of each respective linear system

# 1. from Kreyszig 9th ed. p. 295
a += [np.array([[5,-2],[-1,4]])]
b += [np.array([[20.9],[-19.3]])]

# 3. from Kreyszig 9th ed. p. 295
a += [np.array([[0.5,3.5],[-1,5]])]
b += [np.array([[5.7],[7.8]])]

# 5. from Kreyszig 9th ed. p. 295
a += [np.array([[0.8,-1.2,-0.6],[2.6,0,1.7],[4,7.3,1.5]])]
b += [np.array([[-7.8],[15.3],[1.1]])]

# 7. from Kreyszig 9th ed. p. 295
a += [np.array([[0,1,1],[0,4,6],[1,1,1]])]
b += [np.array([[-2],[-12],[2]])]

# 11. from Kreyszig 9th ed. p. 295
a += [np.array([[2,-1,3],[-4,2,-6]])]
b += [np.array([[-1],[2]])]

# 13. from Kreyszig 9th ed. p. 295
a += [np.array([[0,1,1,-2],[-4,-1,-1,2],[-2,3,3,-6]])]
b += [np.array([[0],[-4],[-2]])]

# 15. from Kreyszig 9th ed. p. 295
a += [np.array([[0,3,7,-4],[5,4,8,1],[8,0,4,-2],[-1,6,0,2]])]
b += [np.array([[-46],[7],[0],[13]])]


In [ ]:
for n, (a1, b1) in enumerate(zip(a, b)):
    try:
        print ("solution", n+1, np.linalg.solve(a1, b1))
    except:
        print ("singular matrix, no solution to linear system", n+1)

In [ ]:
# List comprehension, but no good way to handle exceptions
[np.linalg.solve(a1, b1) for a1, b1 in zip(a, b)]