# DSCI6001-1.2-Lab-Solution

#### 1) Use Numpy to create and store the matrices $A, B, C, D$ and vectors $u, v$.

$$
{\bf A}=
\begin{bmatrix}
3 & 0 & 4 \\
-1 & 2 & 2 \\
6 & 5 & -4
\end{bmatrix},\quad
{\bf B}=
\begin{bmatrix}
0 & -5 & -3 \\
-5 & 2 & 4 \\
-3 & 4 & 0
\end{bmatrix},\quad
{\bf C}=
\begin{bmatrix}
0 & 2 \\
2 & 4 \\
1 & 3
\end{bmatrix},\quad
{\bf D}=
\begin{bmatrix}
6 & 1 \\
-4 & 7 \\
-8 & 3
\end{bmatrix}
$$

$$
\textbf{u}=
\begin{bmatrix}
2 \\
0 \\
1
\end{bmatrix},\quad
\textbf{v}=
\begin{bmatrix}
-4 \\
9 \\
2
\end{bmatrix}
$$

In [23]:
import numpy as np
A = np.array([[3,0,4],[-1,2,2],[6,5,-4]])
B = np.array([[0,-5,-3],[-5,2,4],[-3,4,0]])
C = np.array([[0,2],[2,4],[1,3]])
D = np.array([[6,1],[-4,7],[-8,3]])
u = np.array([[2],[0],[1]])
v = np.array([[-4],[9],[2]])

#### 2) Write code that confirms the shape of the A, B, C, D, u, v.

In [13]:
A.shape

(3, 3)

In [14]:
v.shape

(3, 1)

#### 3) Calculate (in Python):

In [4]:
4*C + 2*D

array([[ 12,  10],
       [  0,  30],
       [-12,  18]])

In [5]:
2*(A+B)

array([[  6, -10,   2],
       [-12,   8,  12],
       [  6,  18,  -8]])

In [25]:
u-v

array([[ 6],
       [-9],
       [-1]])

#### 4) Does $(\textit{A}\textit{B})^{T}$ = $\textit{B}^{T}\textit{A}^{T}$? Produce an assertion that checks for this.

In [7]:
assert ((A*B).T == B.T*A.T).all()

#### 5) Solve the linear system below by hand, then check your answers in Python using [numpy.linalg.solve](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html).

$$
\begin{align}
x + y + 2z & = 3 \\
3x + 4y + 8z & = 10 \\
-2x + 2y + z & = 7
\end{align}
$$


In [27]:
A = np.array([[1,1,2],[3,4,8],[-2,2,1]])
b = np.array([[3],[10],[7]])

x = np.linalg.solve(A, b)
x

array([[ 2.],
       [ 7.],
       [-3.]])