# DSCI6001 1.2 Lab (Graded)

This will be a graded laboratory assignment. 

In [13]:
A = [[3, 0, 4], [-1, 2, 2], [6, 5, -4]]
B = [[0, -5, -3], [-5, 2, 4], [-3, 4, 0]]
C = [[0, 2], [2, 4], [1, 3]]
D = [[6, 1], [-4, 7], [-8, 3]]
u = [2, 0, 1]
v = [-4, 9, 2]

#### 1) Use Numpy to create and store the matrices $A, B, C, D$ and vectors $u, v$.

$$
{\bf A}=
\begin{bmatrix}
3 & 0 & 4 \\
-1 & 2 & 2 \\
6 & 5 & -4
\end{bmatrix},\quad
{\bf B}=
\begin{bmatrix}
0 & -5 & -3 \\
-5 & 2 & 4 \\
-3 & 4 & 0
\end{bmatrix},\quad
{\bf C}=
\begin{bmatrix}
0 & 2 \\
2 & 4 \\
1 & 3
\end{bmatrix},\quad
{\bf D}=
\begin{bmatrix}
6 & 1 \\
-4 & 7 \\
-8 & 3
\end{bmatrix}
$$

$$
\textbf{u}=
\begin{bmatrix}
2 \\
0 \\
1
\end{bmatrix},\quad
\textbf{v}=
\begin{bmatrix}
-4 \\
9 \\
2
\end{bmatrix}
$$

In [71]:
import numpy as np
A = np.asarray(A)
B = np.asarray(B)
C = np.asarray(C)
D = np.asarray(D)
u = np.asarray(u).reshape(3, 1)
v = np.asarray(v).reshape(3, 1)

#### 2) Use Python to determine their dimensions.

In [72]:
Adim = A.shape
Bdim = B.shape
Cdim = C.shape
Ddim = D.shape
udim = u.shape
vdim = v.shape
print("A Dimensions: ", Adim)
print("B Dimensions: ", Bdim)
print("C Dimensions: ", Cdim)
print("D Dimensions: ", Ddim)
print("u Dimensions: ", udim)
print("v Dimensions: ", vdim)

A Dimensions:  (3, 3)
B Dimensions:  (3, 3)
C Dimensions:  (3, 2)
D Dimensions:  (3, 2)
u Dimensions:  (3, 1)
v Dimensions:  (3, 1)


#### 3) Calculate:
* $4C+2D$
* $2(A+B)$
* $u-v$

In [73]:
one = 4*C + 2*D
two = 2*(A + B)
three = u - v
print("Number 1: \n",one)
print("Number 2: \n", two)
print("Number 3: \n", three)

Number 1: 
 [[ 12  10]
 [  0  30]
 [-12  18]]
Number 2: 
 [[  6 -10   2]
 [-12   8  12]
 [  6  18  -8]]
Number 3: 
 [[ 6]
 [-9]
 [-1]]


#### 4) Does $(\textit{A}\textit{B})^{T}$ = $\textit{B}^{T}\textit{A}^{T}$? Produce an assertion that checks for this.

In [65]:
assert np.array_equal(np.transpose(A*B), np.multiply(B.T, A.T))

#### 5) Solve the linear system below by hand, then check your answers in Python using [numpy.linalg.solve](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html).

$$
\begin{align}
x + y + 2z & = 3 \\
3x + 4y + 8z & = 10 \\
-2x + 2y + z & = 7
\end{align}
$$


In [79]:
Alpha = [[1, 1, 2], [3, 4, 8], [-2, 2, 1]]
Beta = [3, 10, 7]
np.linalg.solve(Alpha, Beta).reshape(3, 1)

array([[ 2.],
       [ 7.],
       [-3.]])