# DSCI 6001 - 3.3 Lab Solution: LU Factorization II

Today we are going to code up the algorithm that you wrote down yesterday using the scaffold that I've provided below. Simply follow the prompts. 


In [18]:
import numpy as np
def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    # Nested list comprehension to calculate matrix multiplication (for example). 
    # Converts N into a list of tuples of columns 
    
    
    M = np.asarray(M)
    N = np.asarray(N)
    
    return M.dot(N)

    # The easy answer is cast to np arrays then do M.dot(N)

    #Another way to do so is to a couple of enumerate loops and use the classic matrix product formula:
    # cij = sum a_ik * b_kj


def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # Create an identity matrix, with floating point values. You can also use id_mat = np.identity(n)                                                                                                                                                                                           
    id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M
    
    #for every row in the input matrix
    for j in range(m):
        #find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        # we do not want to be swapping with rows above this one, just the rows below it.
    
        # This is a very minimally compact way to express this logic.
        row = max(range(j, m), key=lambda i: abs(M[i][j]))
        
        # you could have made a dictionary with key, value pairs and found
        # the largest value within a range of keys, reporting the key as 'row'. 
        # There are other ways; a set of for loops would do just fine as well. 
        
        
        if j != row: #if this row is not the row with the next biggest diagonal element
            # Swap the rows of the id matrix                                                                                                                                                                                                                           
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return id_mat

def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    
    for j in range(n):
        
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well, L = np.identity(n)                                                                                                                                                                                                 
        L[j][j] = 1.0

        # LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$                                                                                                                                                                                     
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = PA[i][j] - s1

        # LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in range(j+1, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            print('i', i, 'j', j)
            L[i][j] = (PA[i][j] - s2) / U[j][j]

    return L, U

def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    L = np.asarray([[0.0] * n for i in range(n)])
    U = np.asarray([[0.0] * n for i in range(n)])

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = np.array(mult_matrix(P, A))
    print(L)
    print(U)
    print(PA)
    
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, L, U)


A = np.asarray([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
P, L, U = lu_decomposition(A)

print("A:")
print(A)

print("P:")
print(P)

print("L:")
print(L)

print("U:")
print(U)

print("reconstituted")
print(np.array(P).dot(L).dot(U))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]
i 1 j 0
i 2 j 0
i 3 j 0
i 2 j 1
i 3 j 1
i 3 j 2
A:
[[ 7  3 -1  2]
 [ 3  8  1 -4]
 [-1  1  4 -1]
 [ 2 -4 -1  6]]
P:
[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
L:
[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
U:
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]
[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]


$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$

$l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$ 

In [12]:
id_mat = np.zeros((3,3))

In [13]:
id_mat

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
import numpy as np
def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    # Nested list comprehension to calculate matrix multiplication (for example). 
    # Converts N into a list of tuples of columns 
    
    tuple_N = zip(*N)
    print tuple_N
    
    
    print [sum(m * n for m, n in zip(row_m, col_n)) for col_n in tuple_N]
    
    return [[sum(m * n for m, n in zip(row_m, col_n)) for col_n in tuple_N] for row_m in M]

In [4]:
M = np.asarray([[1,2,0],[0,1,0],[2,3,4]])
N = np.asarray([[1,2],[0,1],[2,3]])

In [11]:
M

array([[1, 2, 0],
       [0, 1, 0],
       [2, 3, 4]])

In [8]:
N

array([[1, 2],
       [0, 1],
       [2, 3]])

In [14]:
for i, row_m in enumerate(M):
    print "row %s: %s" % (i, row_m)

row 0: [1 2 0]
row 1: [0 1 0]
row 2: [2 3 4]


In [7]:
mult_matrix(M,N)

[(1, 0, 2), (2, 1, 3)]


[[1, 4], [0, 1], [10, 19]]

In [23]:
for col_n in zip(*N):
    print sum([m*n for m,n in zip(col_n, M[0])])

1
4
