# RAT 4.3

1. Three points exist on a plane, $k = (4, 1, 3)$, $l = (2, -2, 0)$, $m = (-1, 0, 2)$. Write the normal form equation of this plane.

In [8]:
import numpy as np
k = np.array([[4],[1],[3]])
l = np.array([[2],[-2],[0]])
m = np.array([[-1],[0],[2]])
kl = k-l
ml = m-l

print(kl)
print(ml)

np = np.cross(kl, ml, axisa=0, axisb=0)/np.linalg.norm(np.cross(kl, ml, axisa=0, axisb=0))

print(np)



[[2]
 [3]
 [3]]
[[-3]
 [ 2]
 [ 2]]
[[ 0.         -0.70710678  0.70710678]]


The normal form is $l(t) = t\begin{bmatrix}0\\ -\sqrt{2}\\ \sqrt{2}\end{bmatrix}-\begin{bmatrix}2\\ -2\\ 0\end{bmatrix}$