# RAT 6.1

1. Factor these two vectors to their simplest representation:
   
    $v_1 = \begin{bmatrix}15\\-25\\-5\end{bmatrix}$
    
    $v_2 = \begin{bmatrix}-3\sqrt{15}\\15\sqrt{5}\\-9\sqrt{20}\end{bmatrix}$
    
2. Calculate the inner product of $v_1$ and $v_2$, $v_1^{T}v_2$

3. Make a short list of 5-10 elementary functions

4. What is the formal (equation) definition of the derivative? What does it describe?

5. Calculate the limit derivative of $f(x) = x^{2}$. Show all steps.

6. What is the second whole derivative with respect to x of $f(x) = sin^{2}(x)$? Show all steps and use the chain rule.



v1 = 5*[1, -5, -1]
v2 = -3sqrt(5)*[sqrt(3), -5, -3sqrt(4)]

In [1]:
import numpy as np

#### Answer 2

In [11]:
v1 = np.asarray([[15], [-25], [-5]])
v2 = np.asarray([[-3*np.sqrt(15)], [15*np.sqrt(5)], [-9*np.sqrt(20)]])
print("inner product\n", v1.dot(v2.T))
print("v1^T x v2\n", (v1.T) * (v2))

inner product
 [[ -174.28425058   503.11529494  -603.73835392]
 [  290.47375097  -838.52549156  1006.23058987]
 [   58.09475019  -167.70509831   201.24611797]]
v1^T x v2
 [[ -174.28425058   290.47375097    58.09475019]
 [  503.11529494  -838.52549156  -167.70509831]
 [ -603.73835392  1006.23058987   201.24611797]]


#### answer 3

$g(x) = 4x^2$

$f(x) = e^x$

$f \circ g = e^{4x^2}$

$f(x) = \sqrt{x^2 + 1}$

$g(x) = 2x + 1$

#### answer 4

$$f'(x) = \lim_{\Delta x \rightarrow 0} \frac{f(x + \Delta x) - f(x)}{\Delta x}$$

It describes the slope of a function as we continue to approach a given value on that function.

#### answer 5

$$f'(x) = 2x$$

product rule