# DSCI 6001 5.3 Lab 

## QR Factorization II


## Practical application of the QR algorithm: Stabilized Gram-Schmidt 


Because the GS mapping is so onerous (and numerically unstable) to calculate, and the results so difficult to compare,
there are several ways in which this problem is addressed. The first is by creating the **Modified or Stabilized Gram Schmidt** algorithm, which creates a different Gram-Schmidt factorization (usually in-place) by using normalized vectors as the input in all parts of the computation, making numerical errors much smaller by comparison:

#### Modified Gram-Schmidt


$for\ j\ in\ \{1 \cdots k\}$

  $\ \ \ \ \ for\ i\ in\ \{1 \cdots j-1\}$
  
   $\ \ \ \ \ \ \ \  v_j = v_j - \text{proj}_{v_{i}}v_{j}$
   
   $\ \ \ \ \   v_j = v_{j}/\|v_{j}\|$
            

### TASK:

Implement the MGS algorithm using the below code stub.


In [1]:
import numpy as np

In [50]:
def stabilized_gram_schmidt(a):
    print(a)
    a = a.T
    a = a.astype(float)
    def projection(x, y):
        return ((x.dot(y))/(y.dot(y))) * y 
    
#     def magnitude(x):
#         for i in x:
#             mag = np.asarray([np.sqrt(sum(x[i]**2))])
#         return mag
                           
    for j in range(len(a)):
        for i in range(j):
            a[j] = a[j] - projection(a[j], a[i])
        a[j] = a[j]/np.linalg.norm(a[j])
    
        
    # * I recommend getting the number of columns (or rows if you prefer to flip the matrix)
    # * make sure your matrix A is cast into floats
    # * begin the top for loop
            #* begin the bottom for loop
                    # * use the projection subtraction here:
                    # remove projection of a[j] over a[i] from a[j]
            # * normalize the column (or row) you're working through

    return a.T # * return the matrix here. don't rely on pass-by-reference

In [58]:
print([item for item in range(0)])

[]


In [52]:
a = np.asarray([[-2, 0, 1], [1, -2, 1], [1, -1, 0]])

In [53]:
stabilized_gram_schmidt(a)

[[-2  0  1]
 [ 1 -2  1]
 [ 1 -1  0]]


array([[-0.81649658, -0.53452248, -0.21821789],
       [ 0.40824829, -0.80178373,  0.43643578],
       [ 0.40824829, -0.26726124, -0.87287156]])

In [55]:
# Quick test harness

A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])
Q = stabilized_gram_schmidt(A)
R = Q.dot(A)

R = Q.T.dot(A)
print(Q)
print(Q.dot(R))


[[-2  0  1]
 [ 1 -2  1]
 [ 1 -1  0]]
[[-0.81649658 -0.53452248 -0.21821789]
 [ 0.40824829 -0.80178373  0.43643578]
 [ 0.40824829 -0.26726124 -0.87287156]]
[[ -2.00000000e+00  -2.90724631e-16   1.00000000e+00]
 [  1.00000000e+00  -2.00000000e+00   1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00   6.24796589e-16]]


In [56]:
# worked with Jonathan H. and Carles on this