### DSCI6001 2.1 Lab

This will be a graded laboratory assignment of approximately 30 minutes.

Review [numpy.linalg.solve](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html). 

1) Create matrices representing the linear systems in Kreyszig Chapter 7 (9th ed. page 330) problems 12, 14, 16, 18.
      

In [3]:
import numpy as np

In [53]:
twelveA = np.asarray([[-2, -4, 7], [1, 2, 16]])
twelveB = np.asarray([-6, 3]).reshape(2, 1)
fourteenA = np.asarray([[5, -10], [3, 1], [-1, 6]])
fourteenB = np.asarray([2, 13, 6]).reshape(3, 1)
sixteenA = np.asarray([[0, 2, 1], [2, 3, -1], [5, -4, 3]])
sixteenB = np.asarray([-1, -12, 32]).reshape(3, 1)
eighteenA = np.asarray([[-1, 4, -2], [3, 4, 6], [1, -2, 2]])
eighteenB = np.asarray([1, 1, -0.5]).reshape(3, 1)

2) Confirm the shapes of the coefficient matrices, by inspection or using Python. Which of these can numpy solve? Use numpy to solve the systems it can solve. Explain the solution set to the systems numpy cannot solve.
   

In [49]:
twelveA.shape

(2, 3)

In [57]:
np.linalg.solve(twelveA, twelveB)
# twelve can't be solved because it's trying to multiply a 2x3 matrix by a 2x1 matrix

LinAlgError: Last 2 dimensions of the array must be square

In [50]:
fourteenA.shape

(3, 2)

In [61]:
np.linalg.solve(fourteenA, fourteenB)
# fourteen can't be solved because it's trying to multiply a 3x2 matrix by a 3x1 matrix

LinAlgError: Last 2 dimensions of the array must be square

In [55]:
sixteenA.shape

(3, 3)

In [59]:
np.linalg.solve(sixteenA, sixteenB)

array([[ 1.],
       [-3.],
       [ 5.]])

In [56]:
eighteenA.shape

(3, 3)

In [60]:
np.linalg.solve(eighteenA, eighteenB)
# this should be unsolvable because eighteenA has a zero Determinant

array([[-0.5 ],
       [ 0.25],
       [ 0.25]])

In [65]:
np.round(np.linalg.det(eighteenA))

-0.0

3) Create numpy  matrices A and B, and vectors a, b from Kreyszig Chapter 7 (9th ed. page 331). Using Python, calculate:
* AB, BA
* $\textit{A}\textit{A}^{T}$
* $\textit{B}^{T}\textit{A}$
* $\textit{a}^{T}\textit{b}$
* $\textit{b}^{T}\textit{a}$
* $\textit{ab}^{T}$    
* $\textit0.1({A}+{A}^{T})({B}-{B}^{T})$

In [69]:
A = np.asarray([[9, 2, 8], [2, 18, 10], [8, 10, 15]])
B = np.asarray([[0, 2, 6], [-2, 0, -3], [-6, 3, 0]])
a = np.asarray([3, 7, 1]).reshape(3, 1)
b = np.asarray([4, 0, 2]).reshape(3, 1)

In [73]:
A.dot(B)

array([[ -52,   42,   48],
       [ -96,   34,  -42],
       [-110,   61,   18]])

In [74]:
B.dot(A)

array([[ 52,  96, 110],
       [-42, -34, -61],
       [-48,  42, -18]])

In [75]:
A.dot(A.T)

array([[149, 134, 212],
       [134, 428, 346],
       [212, 346, 389]])

In [76]:
(B.T).dot(A)

array([[ -52,  -96, -110],
       [  42,   34,   61],
       [  48,  -42,   18]])

In [77]:
(a.T).dot(b)

array([[14]])

In [78]:
a.dot(b.T)

array([[12,  0,  6],
       [28,  0, 14],
       [ 4,  0,  2]])

In [85]:
-1 * (A + A.T).dot(B - B.T)

array([[ 208, -168, -192],
       [ 384, -136,  168],
       [ 440, -244,  -72]])

4) According to the [Pew Research Center](http://www.pewsocialtrends.org/2015/12/09/the-american-middle-class-is-losing-ground/), America in 1970 was 10% lower, 62% middle, and 28% upper class. Create a simple Markov process to model the decades from 1970 to 2070, using the following estimates that per decade... 
* Lower class has a 5% chance of becoming middle class, 1% of upper class
* Middle class has a 10% chance of lower class, and a 5% chance upper class
* Upper class: 5% chance become lower class, 10% become middle class

In [97]:
A = np.asarray([.1, .62, .28]) #prior state
B = np.asarray([[.94, 0.05, .01], [.1, .85, .05], [.05, .1, .85]]) #stochastic matrix

for i in range(11):
    print('In ', i, 'decades, we have:')
    print(np.linalg.matrix_power(B.T,i).dot(A))

In  0 decades, we have:
[ 0.1   0.62  0.28]
In  1 decades, we have:
[ 0.17  0.56  0.27]
In  2 decades, we have:
[ 0.2293  0.5115  0.2592]
In  3 decades, we have:
[ 0.279652  0.47216   0.248188]
In  4 decades, we have:
[ 0.32249828  0.4401374   0.23736432]
In  5 decades, we have:
[ 0.35903034  0.41397814  0.22699152]
In  6 decades, we have:
[ 0.39023591  0.39253209  0.21723201]
In  7 decades, we have:
[ 0.41693656  0.37488727  0.20817617]
In  8 decades, we have:
[ 0.4398179   0.36031862  0.19986347]
In  9 decades, we have:
[ 0.45945387  0.34824807  0.19229806]
In  10 decades, we have:
[ 0.47632634  0.33821336  0.18546029]
