# RAT 4.1

1. Describe the three component matrices of an SVD.
2. What special properties do the three component matrices have?
3. Use numpy (not linalg.svd) to calculate a solution to the SVD of $A = \begin{bmatrix}1 & -1\\3 & 1\end{bmatrix}$. You will need to use linalg.eig.

1. $A = U\ \Delta\ V^{T}$, $\Delta$ is a diagonal matrix of singular values. $U$ is the matrix of eigenvectors belonging to $AA^{T}$ and V is the matrix of eigenvectors belonging to $A^{T}A$. 

2. Both $U$ and $V$ are real-valued, orthonormal matrices. $\Delta$ is a diagonal matrix of singular values. 

In [1]:
import numpy as np
A = np.array([[1, -1],[3, 1]])
print(A)
AAt = A.dot(A.T)
AtA = A.T.dot(A)
assert AAt.shape == AtA.shape

Su, U = np.linalg.eigh(AAt)
Sv, V = np.linalg.eigh(AtA)

print(Su, Sv)
print(U)
print(V)
A = U.dot(np.diag(np.sqrt(Sv))).dot(V.T)
print(A) # A is often off by a sign due to the output of eig

[[ 1 -1]
 [ 3  1]]
[  1.52786405  10.47213595] [  1.52786405  10.47213595]
[[-0.97324899  0.22975292]
 [ 0.22975292  0.97324899]]
[[ 0.22975292 -0.97324899]
 [-0.97324899 -0.22975292]]
[[-1.  1.]
 [-3. -1.]]
