# DSCI6001 1.4.Lab (Graded)

This will be a graded laboratory assignment of approximately 30 minutes.

In yesterday's lecture you were assigned from Kreyszig 9th ed.

#### Reading 
* 7.4, 7.5, 7.7

#### Problems 
* 7.4: 1, 3, 7, 11, 15, 19, 27, 33, 35
* 7.7: 5, 7, 11, 14, 19, 21

If you have completed the above assigments, you may proceed with the lab.

## Lab

Solve using Python. Hint: search the numpy documentation.

1. Write a Python function `randomat` that returns a random square numpy matrix of integers of given dimension n. The integers should be between -1 and 3. 

2. Create a list containing 50 `randomat` 3x3 matrices. Make a copy of the list, in the form of a Pandas `Series`. Hint: Solution provided below.

3. Create a list of the the 50 *determinants* of the 50 matrices. Make a copy of the list, in the form of a Pandas `Series`.

4.  Create a list of the the 50 *ranks* of the 50 matrices. Make a copy of the list, in the form of a Pandas `Series`.

5. Extract two suitable matrices from your array into variables A and B, then write assertions to test the following Inversion Properties:

    1. $({\bf A}^{-1})^{-1} = {\bf A}$
    2. $({\bf AB})^{-1} = {\bf B}^{-1} {\bf A}^{-1}$  Hint: Solution below
    3. $|{\bf AB}| = |{\bf A}| ~ |{\bf B}| = |{\bf BA}|$
    4. $|{\bf A}^T| = |{\bf A}|$
    5. $|{\bf A}^{-1}| = \frac{1}{|{\bf A}|}$
    
6. Exactly how many of your randomly generated matrices were unsuitable for exercise 5. What makes them unsuitable? 


In [8]:
import pandas as pd
import numpy as np

def randomat(n):
    return np.random.random_integers(-1, 3, (n, n))
    

# 2. You can use a for loop, or here is a solution using a list comprehension
matrix_list = [randomat(3) for _ in range(50)]

# Convert the list into a Series. Both forms have their uses.
matrix_Series = pd.Series (matrix_list)


In [9]:
randomat(3)

array([[3, 1, 1],
       [3, 0, 2],
       [3, 0, 3]])

In [10]:
matrix_Series = pd.Series ([randomat(3) for _ in range(50)])
det_Series = pd.Series(np.linalg.det([_ for _ in matrix_Series]))
rank_Series = pd.Series(np.linalg.matrix_rank(_) for _ in matrix_Series)

In [11]:
matrix_Series

0         [[0, 0, 1], [2, 1, -1], [1, 3, 0]]
1         [[2, 1, 1], [-1, 2, 3], [1, 1, 1]]
2       [[2, 1, -1], [0, 1, -1], [0, 3, -1]]
3         [[0, -1, 0], [2, 0, 0], [3, 0, 3]]
4        [[2, 2, 2], [2, -1, 2], [0, 0, -1]]
5         [[2, 2, 0], [1, 3, 0], [0, -1, 3]]
6        [[1, 3, -1], [0, 0, 0], [1, 2, -1]]
7         [[3, -1, 2], [0, 0, 2], [2, 3, 0]]
8         [[0, 1, -1], [2, 0, 0], [2, 0, 0]]
9          [[0, 3, 1], [3, 0, 3], [1, 0, 3]]
10      [[0, 2, -1], [2, -1, 1], [0, -1, 1]]
11         [[1, 3, 0], [2, 3, 0], [2, 1, 2]]
12       [[-1, 0, 1], [-1, 2, 1], [1, 2, 2]]
13       [[-1, 3, 3], [-1, 1, 3], [2, 2, 3]]
14        [[2, 3, 0], [1, -1, 3], [3, 3, 1]]
15      [[2, 1, 3], [2, 3, -1], [3, -1, -1]]
16      [[3, -1, -1], [2, 3, 3], [-1, 1, 3]]
17      [[2, 2, -1], [-1, 2, 1], [2, 3, -1]]
18        [[3, 2, 1], [1, 2, 1], [3, 2, -1]]
19        [[1, 1, 2], [2, 0, -1], [1, 3, 2]]
20        [[3, 0, -1], [1, 2, 1], [3, 2, 3]]
21       [[1, 2, -1], [2, -1, 1], [0, 3, 0]]
22        

In [12]:
det_Series

0      5.0
1     -1.0
2      4.0
3      6.0
4      6.0
5     12.0
6      0.0
7    -22.0
8      0.0
9    -18.0
10    -2.0
11    -6.0
12    -6.0
13    18.0
14     4.0
15   -42.0
16    22.0
17    -1.0
18    -8.0
19    10.0
20    16.0
21    -9.0
22     0.0
23     0.0
24    -2.0
25     7.0
26   -12.0
27     9.0
28    35.0
29     3.0
30    10.0
31     7.0
32    -6.0
33   -25.0
34    -5.0
35    -9.0
36   -18.0
37     3.0
38    22.0
39    -3.0
40    11.0
41     2.0
42     1.0
43    18.0
44   -24.0
45     3.0
46     7.0
47     6.0
48   -32.0
49     1.0
dtype: float64

In [13]:
rank_Series

0     3
1     3
2     3
3     3
4     3
5     3
6     2
7     3
8     2
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    3
21    3
22    2
23    2
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    3
dtype: int64

In [84]:
nz = np.nonzero(det_Series)
nz

(array([ 0,  1,  2,  3,  4,  5,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [91]:
AB = np.random.choice(matrix_Series[pd.Series(np.nonzero(det_Series))[0]], 2)
AB

array([array([[-1,  0,  0],
       [ 0,  2, -1],
       [-1, -1,  0]]),
       array([[ 0,  0,  3],
       [-1, -1,  2],
       [ 1,  2,  2]])], dtype=object)

In [92]:
A = AB[0]
B = AB[1]
Ainv = np.linalg.inv(A)
Binv = np.linalg.inv(B)
Adet = np.linalg.det(A)
Bdet = np.linalg.det(B)

In [ ]:
# (A−1)−1=A
# (AB)−1=B−1A−1 Hint: Solution below
# |AB|=|A| |B|=|BA|
# |AT|=|A|
# |A−1|=1|A|

In [93]:
#(A^−1)^−1=A
assert np.array_equal(np.rint(np.linalg.inv(Ainv)), A)

In [94]:
#(AB)^−1=B^−1A^−1
from numpy.linalg import det, inv
from numpy import allclose
assert np.allclose(inv(A.dot(B)), Binv.dot(Ainv))

In [104]:
#|AB|=|A||B|=|BA|
assert np.round(np.linalg.det(A.dot(B))) == int(Adet)*int(Bdet) == np.round(np.linalg.det(B.dot(A)))

In [105]:
#|AT|=|A|
assert np.linalg.det(A.T) == Adet

In [106]:
#|A−1|=1/|A|
assert np.round(np.linalg.det(Ainv), 2) == (1 / Adet)

In [107]:
unsuitable_for_exercise5 = len(det_Series) - np.count_nonzero(det_Series)
print("Exactly", unsuitable_for_exercise5, "were unsuitable.")
print("This is because their Determinant was equal to 0, which by definition,\nmakes them infinite/no solution and uninvertible")

Exactly 4 were unsuitable.
This is because their Determinant was equal to 0, which by definition,
makes them infinite/no solution and uninvertible
